//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESO.Amerra_Docs.MerlinWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="gsNotificacionesMerlinResult", Namespace="http://schemas.datacontract.org/2004/07/GS.SISGEGS.DM")]
    [System.SerializableAttribute()]
    public partial class gsNotificacionesMerlinResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsuntoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNotificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asunto {
            get {
                return this.AsuntoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsuntoField, value) != true)) {
                    this.AsuntoField = value;
                    this.RaisePropertyChanged("Asunto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailCC {
            get {
                return this.EmailCCField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailCCField, value) != true)) {
                    this.EmailCCField = value;
                    this.RaisePropertyChanged("EmailCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailTO {
            get {
                return this.EmailTOField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailTOField, value) != true)) {
                    this.EmailTOField = value;
                    this.RaisePropertyChanged("EmailTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNotificacion {
            get {
                return this.IdNotificacionField;
            }
            set {
                if ((this.IdNotificacionField.Equals(value) != true)) {
                    this.IdNotificacionField = value;
                    this.RaisePropertyChanged("IdNotificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MerlinWCF.IMerlinWCF")]
    public interface IMerlinWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerlinWCF/NotificacionMerlin", ReplyAction="http://tempuri.org/IMerlinWCF/NotificacionMerlinResponse")]
        TESO.Amerra_Docs.MerlinWCF.gsNotificacionesMerlinResult[] NotificacionMerlin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerlinWCF/NotificacionMerlin", ReplyAction="http://tempuri.org/IMerlinWCF/NotificacionMerlinResponse")]
        System.Threading.Tasks.Task<TESO.Amerra_Docs.MerlinWCF.gsNotificacionesMerlinResult[]> NotificacionMerlinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerlinWCF/ActualizarNotificacionMerlin", ReplyAction="http://tempuri.org/IMerlinWCF/ActualizarNotificacionMerlinResponse")]
        void ActualizarNotificacionMerlin(int idNotificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMerlinWCF/ActualizarNotificacionMerlin", ReplyAction="http://tempuri.org/IMerlinWCF/ActualizarNotificacionMerlinResponse")]
        System.Threading.Tasks.Task ActualizarNotificacionMerlinAsync(int idNotificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMerlinWCFChannel : TESO.Amerra_Docs.MerlinWCF.IMerlinWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MerlinWCFClient : System.ServiceModel.ClientBase<TESO.Amerra_Docs.MerlinWCF.IMerlinWCF>, TESO.Amerra_Docs.MerlinWCF.IMerlinWCF {
        
        public MerlinWCFClient() {
        }
        
        public MerlinWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MerlinWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerlinWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MerlinWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TESO.Amerra_Docs.MerlinWCF.gsNotificacionesMerlinResult[] NotificacionMerlin() {
            return base.Channel.NotificacionMerlin();
        }
        
        public System.Threading.Tasks.Task<TESO.Amerra_Docs.MerlinWCF.gsNotificacionesMerlinResult[]> NotificacionMerlinAsync() {
            return base.Channel.NotificacionMerlinAsync();
        }
        
        public void ActualizarNotificacionMerlin(int idNotificacion) {
            base.Channel.ActualizarNotificacionMerlin(idNotificacion);
        }
        
        public System.Threading.Tasks.Task ActualizarNotificacionMerlinAsync(int idNotificacion) {
            return base.Channel.ActualizarNotificacionMerlinAsync(idNotificacion);
        }
    }
}
