//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESO.Amerra_Docs.CorreoWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CorreoWCF.ICorreoWCF")]
    public interface ICorreoWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorreoWCF/EnviarCorreo", ReplyAction="http://tempuri.org/ICorreoWCF/EnviarCorreoResponse")]
        void EnviarCorreo(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorreoWCF/EnviarCorreo", ReplyAction="http://tempuri.org/ICorreoWCF/EnviarCorreoResponse")]
        System.Threading.Tasks.Task EnviarCorreoAsync(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorreoWCF/MerlinEnviarCorreo", ReplyAction="http://tempuri.org/ICorreoWCF/MerlinEnviarCorreoResponse")]
        void MerlinEnviarCorreo(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorreoWCF/MerlinEnviarCorreo", ReplyAction="http://tempuri.org/ICorreoWCF/MerlinEnviarCorreoResponse")]
        System.Threading.Tasks.Task MerlinEnviarCorreoAsync(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorreoWCF/MerlinEnvioCorreoAdjunto", ReplyAction="http://tempuri.org/ICorreoWCF/MerlinEnvioCorreoAdjuntoResponse")]
        void MerlinEnvioCorreoAdjunto(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje, string FilePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorreoWCF/MerlinEnvioCorreoAdjunto", ReplyAction="http://tempuri.org/ICorreoWCF/MerlinEnvioCorreoAdjuntoResponse")]
        System.Threading.Tasks.Task MerlinEnvioCorreoAdjuntoAsync(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje, string FilePath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICorreoWCFChannel : TESO.Amerra_Docs.CorreoWCF.ICorreoWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorreoWCFClient : System.ServiceModel.ClientBase<TESO.Amerra_Docs.CorreoWCF.ICorreoWCF>, TESO.Amerra_Docs.CorreoWCF.ICorreoWCF {
        
        public CorreoWCFClient() {
        }
        
        public CorreoWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorreoWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorreoWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorreoWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EnviarCorreo(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje) {
            base.Channel.EnviarCorreo(to, toCorreo, cc, ccCorreo, asunto, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarCorreoAsync(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje) {
            return base.Channel.EnviarCorreoAsync(to, toCorreo, cc, ccCorreo, asunto, mensaje);
        }
        
        public void MerlinEnviarCorreo(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje) {
            base.Channel.MerlinEnviarCorreo(to, toCorreo, cc, ccCorreo, asunto, mensaje);
        }
        
        public System.Threading.Tasks.Task MerlinEnviarCorreoAsync(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje) {
            return base.Channel.MerlinEnviarCorreoAsync(to, toCorreo, cc, ccCorreo, asunto, mensaje);
        }
        
        public void MerlinEnvioCorreoAdjunto(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje, string FilePath) {
            base.Channel.MerlinEnvioCorreoAdjunto(to, toCorreo, cc, ccCorreo, asunto, mensaje, FilePath);
        }
        
        public System.Threading.Tasks.Task MerlinEnvioCorreoAdjuntoAsync(string to, string toCorreo, string cc, string ccCorreo, string asunto, string mensaje, string FilePath) {
            return base.Channel.MerlinEnvioCorreoAdjuntoAsync(to, toCorreo, cc, ccCorreo, asunto, mensaje, FilePath);
        }
    }
}
